# Recommended location for database
db_file            "/home/ella/.config/mpd/database"

# Logs to systemd journal
log_file           "syslog"

# The music directory is by default the XDG directory, uncomment to amend and choose a different directory
music_directory    "/home/ella/Music"

# Uncomment to refresh the database whenever files in the music_directory are changed
auto_update "yes"
auto_update_depth "3"
log_level            "verbose"
follow_outside_symlinks    "yes"
follow_inside_symlinks        "yes"

# Uncomment to enable the functionalities
playlist_directory "~/.config/mpd/playlists"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"

audio_output {
        type            "pulse"
        name            "pulse audio"
}

audio_output {
        type            "httpd"
        name            "http"
        port            "4343"
        bind_to_address "0.0.0.0"
        quality         "9"
        format          "44100:16:1"
}

audio_output {
    type                    "fifo"
    name                    "ncmpcpp_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

bind_to_address "127.0.0.1"
